name: Gradle Build and Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: aethersky/interval

jobs:

  build-gradle-docker:

    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - uses: actions/checkout@v4

    - name: Build with Gradle Wrapper
      run: ./gradlew html:dist

    - name: look at directories
      run: tree

    - name: Run Bash script
      run: bash ./mkbuild.sh

    - name: look at directories (again)
      run: tree

    - name: make tag name
      run: echo $(date +%s) >> ./dist/tagname

    - name: Build the Docker image
      working-directory: ./dist/
      run: docker build . --file Dockerfile --tag aethersky/interval:$(cat ./tagname)

    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push the Docker image
      working-directory: ./dist/
      run: docker push docker.io/aethersky/interval:$(cat ./tagname)
    #- name: Extract metadata (tags, labels) for Docker
    #  id: meta
    #  uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
    #  with:
    #    images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    #- name: Build and push Docker image
    #  uses: docker/build-push-action@v2
    #  with:
    #    context: "{{defaultContext}}"
    #    push: true
    #    tags: ${{ steps.meta.outputs.tags }}
    #    labels: ${{ steps.meta.outputs.labels }}


